# Generated by Django 2.2.12 on 2020-04-20 09:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercise', '0004_complaint_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Patient',
        ),
    ]
