# Generated by Django 2.2.12 on 2020-04-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_auto_20200420_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='complaints',
            field=models.TextField(blank=True, default=''),
        ),
    ]
