# Generated by Django 2.2.12 on 2020-10-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_auto_20200503_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='owner',
        ),
    ]
