# Generated by Django 2.2.12 on 2020-10-06 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0010_auto_20200420_1458'),
        ('assignment', '0006_remove_assignment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='exercise.Patient'),
            preserve_default=False,
        ),
    ]
