# Generated by Django 2.2.17 on 2020-11-06 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_auto_20201106_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='exercise.Patient'),
        ),
    ]
