# Generated by Django 2.2.11 on 2020-03-18 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kine', '0003_auto_20200316_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='kine.Patient'),
        ),
    ]
