# Generated by Django 2.2.11 on 2020-03-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kine', '0004_auto_20200318_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='excercise',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
