# Generated by Django 2.2.11 on 2020-04-02 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practictioner',
            name='user',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Excercise',
        ),
        migrations.DeleteModel(
            name='Practictioner',
        ),
    ]
