# Generated by Django 2.2.11 on 2020-04-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Therapist'), (2, 'Patient')], default=2, null=True),
        ),
    ]
